// <auto-generated />
namespace UBOnlineWebApiTest2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Exam2Added1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exam2Added1));
        
        string IMigrationMetadata.Id
        {
            get { return "201312012236471_Exam2Added1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
