// <auto-generated />
namespace UBOnlineWebApiTest2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AToA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AToA));
        
        string IMigrationMetadata.Id
        {
            get { return "201312130444298_AToA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
